version: "3.8"

services:
  pg:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: gunicorn --access-logfile -k uvicorn.workers.UvicornWorker --workers 3 --bind 0.0.0.0:8000 main:app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      pg:
        condition: service_healthy
    env_file:
      - ./.env
volumes:
  db-data: